create table if not exists public.phishing_logs (
    id bigint generated by default as identity primary key,
    url text not null,
    score double precision,
    risk_level text not null,
    status varchar(50) not null,
    reason text,
    computer_number integer,
    campus_name varchar(100),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.phishing_logs
    add column if not exists url text,
    add column if not exists score double precision,
    add column if not exists risk_level text,
    add column if not exists status varchar(50),
    add column if not exists reason text,
    add column if not exists computer_number integer,
    add column if not exists campus_name varchar(100),
    add column if not exists metadata jsonb not null default '{}'::jsonb,
    add column if not exists created_at timestamptz not null default now();

create index if not exists phishing_logs_created_at_index
    on public.phishing_logs (created_at desc);

create index if not exists phishing_logs_risk_level_index
    on public.phishing_logs (risk_level);

create index if not exists phishing_logs_campus_name_index
    on public.phishing_logs (campus_name);

alter table public.phishing_logs enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant insert on table public.phishing_logs to anon, authenticated;
grant select, insert, update, delete on table public.phishing_logs to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

drop policy if exists "API clients can create phishing logs" on public.phishing_logs;
create policy "API clients can create phishing logs"
    on public.phishing_logs
    for insert
    to anon, authenticated
    with check (
        char_length(url) between 1 and 4096
        and risk_level in ('Safe', 'Low', 'Medium', 'High', 'Critical')
        and (score is null or score between 0 and 1)
        and (computer_number is null or computer_number > 0)
    );
